// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Role,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  groupId: __t.u64().name("group_id"),
  profileId: __t.identity().name("profile_id"),
  get role() {
    return Role;
  },
  joinedAt: __t.timestamp().name("joined_at"),
});
