// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Availability = __t.object("Availability", {
  id: __t.u64(),
  profileId: __t.identity(),
  dayOfWeek: __t.u64(),
  startTime: __t.string(),
  endTime: __t.string(),
});
export type Availability = __Infer<typeof Availability>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  groupId: __t.u64(),
  title: __t.string(),
  description: __t.option(__t.string()),
  startTime: __t.timestamp(),
  endTime: __t.timestamp(),
  location: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Group = __t.object("Group", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  code: __t.string(),
  ownerId: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Group = __Infer<typeof Group>;

export const GroupMember = __t.object("GroupMember", {
  id: __t.u64(),
  groupId: __t.u64(),
  profileId: __t.identity(),
  get role() {
    return Role;
  },
  joinedAt: __t.timestamp(),
});
export type GroupMember = __Infer<typeof GroupMember>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  email: __t.string(),
  name: __t.option(__t.string()),
  timezone: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Profile = __Infer<typeof Profile>;

// The tagged union or sum type for the algebraic type `Role`.
export const Role = __t.enum("Role", {
  Admin: __t.unit(),
  Member: __t.unit(),
});
export type Role = __Infer<typeof Role>;

