// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateGroupReducer from "../create_group_reducer";
import CreateProfileReducer from "../create_profile_reducer";
import JoinGroupReducer from "../join_group_reducer";
import LeaveGroupReducer from "../leave_group_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type CreateGroupParams = __Infer<typeof CreateGroupReducer>;
export type CreateProfileParams = __Infer<typeof CreateProfileReducer>;
export type JoinGroupParams = __Infer<typeof JoinGroupReducer>;
export type LeaveGroupParams = __Infer<typeof LeaveGroupReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

